kind: Deployment
apiVersion: apps/v1
metadata:
   name: coffee
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: app
   template:
      metadata:
        labels:
          app: app
      spec:
       containers:
        - name: coffe
          image: spockiscoding/meusite:3.0 #image_name_dockerhub
          imagePullPolicy: Always
          ports:
          - containerPort: 80
