kind: Deployment
apiVersion: apps/v1
metadata:
   name: minha_aplicacao
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: minha_aplicacao
   template:
      metadata:
        labels:
          app: minha_aplicacao
      spec:
       containers:
        - name: minha_aplicacao
          image: shazabtanveer/project #image_name_dockerhub
          imagePullPolicy: Always
          ports:
          - containerPort: 80
