kind: Service                             
apiVersion: v1
metadata:
  name: minha_aplicacao
  labels:
    app: minha_aplicacao
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: mrdevops                    
  type: LoadBalancer   
