kind: Service                             
apiVersion: v1
metadata:
  name: coffee
  labels:
    app: app
spec:
  ports:
    - port: 8085                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: app                    
  type: NodePort  
